version: 2

updates:
  # Composer: 1x weekly for minor/patch, 1x monthly for major.
  - package-ecosystem: 'composer'
    directories:
      - '/apps/wordpress/composer.json'
      - '/apps/wordpress/composer.lock'
    schedule:
      interval: 'weekly'
    cooldown:
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 7
    groups:
      composer-dev-minor-patch:
        dependency-type: 'development'
        update-types: [minor, patch]
      composer-dev-major:
        dependency-type: 'development'
        update-types: [major]
      # We don't bundle minor or major production assets, so they're tested individually.
      composer-patch:
        dependency-type: 'production'
        update-types: [patch]

  # NPM: 1x weekly for minor/patch, 1x monthly for major.
  - package-ecosystem: 'npm'
    directories:
      - '/package.json'
      - '/package-lock.json'
      - '/apps/api/package.json'
      - '/apps/chat/package.json'
      - '/apps/dashboard/package.json'
      - '/apps/rag/package.json'
      - '/apps/wordpress/package.json'
      - '/apps/wordpress/package-lock.json'
      # @todo add other plugin directories when their dependency trees are stabilized.
    schedule:
      interval: 'weekly'
    cooldown:
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 7
    groups:
      npm-minor-patch:
        update-types: [minor, patch]
      npm-dev-major:
        dependency-type: 'development'
        update-types: [major]

  # GitHub Actions: 1x weekly.
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      github-actions-updates:
        patterns: ['*']

  # Docker: 1x weekly.
  - package-ecosystem: 'docker'
    directories:
      - '/apps/api/Dockerfile'
      - '/apps/chat/Dockerfile'
      - '/apps/dashboard/Dockerfile'
      - '/apps/nlp/Dockerfile'
    schedule:
      interval: 'weekly'
    groups:
      docker-updates:
        patterns: ['*']

  # PIP: 1x weekly for minor/patch, 1x monthly for major.
  - package-ecosystem: 'pip'
    directories:
      - '/apps/nlp/requirements.txt'
    schedule:
      interval: 'weekly'
    cooldown:
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 7
    groups:
      pip-minor-patch:
        update-types: [minor, patch]
      pip-major:
        update-types: [major]
